### ISSUE TITLE
Support for simple arrays in YAML samplesheets

### ISSUE THREAD

**Issue by awgymer** [nextflow-io/nf-validation#78]
It would be great to be able to supply an arbitrary length array of files that is associated with just one other file like so:

```yaml
---
- id: sample1
  normal: /path/to/some/file.bam
  tumour:
    - /path/to/tumour1.bam
    - /path/to/tumour2.bam
  cancer_type: aml
```

And then I would want to create some channel like: `[[id: sample1], [normal_bam], [tumour_bams]]`

In a perfect world that would be possible via `fromSamplesheet` but for now I would be happy with just having the samplesheet schema validation.
